Quiz/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


app_name = 'Quiz'


urlpatterns = [
    path('certificate/<int:verification>',views.certificate,name="certificate"),
    path('Slide/<int:that_slide_no>', views.slide, name="slide"),
    path('Submission/<int:that_quiz_id>', views.Submission, name="Submission"),
    path('question/<int:that_quiz_id>', views.question, name="question"),
    path('Mquiz/', views.Mquiz, name="Mquiz"),
    path('Score/<int:verification>', views.Score, name="Score"),

]

QuizSystem/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from Quiz import views

urlpatterns = [
    path('', views.Mquiz, name="Mquiz"),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('Quiz/', include('Quiz.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    # path('AAaccounts/',views.AAaccounts,name="AAaccounts"),
    path('analysis/',views.analysis,name="analysis"),
    path('adminPanel/',views.adminPanel,name="adminPanel"),
    path('adminDashboard/',views.adminDashboard,name="adminDashboard"),
    path('registration_view/', views.registration_view, name="registration_view"),
    path('login_view/', views.login_view, name="login_view"),
    path('logout_view/', views.logout_view, name="logout_view"),
    path('mysubmissions/', views.mysubmissions, name="mysubmissions"),
    path('password/',views.change_password, name='change_password'),
]

Quiz/models.py
from django.db import models
# from django.contrib.auth.models import User
from account.models import Account
from cloudinary.models import CloudinaryField
import cloudinary

import uuid

# Create your models here.
class CustomizeQuiz(models.Model):
    title = models.CharField(max_length=200, default="Empty")
    description = models.TextField(max_length=2000, default=" ")

    def __str__(self):
        return (self.title)

    objects = models.Manager()
    class meta:
        managed = True
        db_table = 'CustomizeQuiz'

class Tquestion(models.Model):
    that_Quiz = models.ForeignKey(CustomizeQuiz, on_delete=models.CASCADE,default="")
    no = models.PositiveIntegerField(primary_key=True)
    question = models.CharField(max_length=1000, default=" ")
    A = models.CharField(max_length=500, default=" ")
    B = models.CharField(max_length=500, default=" ")
    C = models.CharField(max_length=500,default=" ")
    D = models.CharField(max_length=500, default=" ")
    answer = models.CharField(max_length=500, default=" ")
    def __str__(self):
        return str("("+str(self.no)+")"+self.question)

    objects = models.Manager()
    class meta:
        managed = True
        db_table = 'Tquestion'

class Myself(models.Model):
    # id = models.AutoField(primary_key=True,default=None)
    me = models.ForeignKey(Account, on_delete=models.CASCADE, default="")
    answer = models.CharField(max_length=100, default="")
    correct = models.IntegerField(default=0)
    wrong = models.IntegerField(default=0)
    percentage = models.IntegerField(default=0)
    urlhash = models.UUIDField(default=uuid.uuid4, editable=False)
    timeStamp = models.DateTimeField(auto_now_add=True)
    
    def urlH(self):
        urlH = int(self.urlhash)
        return urlH

    def __str__(self):
        return str(str(self.me)+"("+self.answer+")")

    def total(self):
        total = self.correct + self.wrong
        return total

    objects = models.Manager()
    class meta:
        managed = True
        db_table = 'Myself'

class Slide(models.Model):
    no = models.PositiveIntegerField(default=None)
    title = models.CharField(max_length=200,blank=True)
    description = models.TextField(max_length=4000,blank=True)
    # image = models.ImageField(blank=True)
    image = cloudinary.models.CloudinaryField('image',blank=True)

    def __str__(self):
        return ("("+ str(self.no) +")"+ self.title)
    
    objects = models.Manager()

class Department_or_branch(models.Model):
    Department_or_branch_name = models.CharField(max_length=100, default="")
    def __str__(self):
        return self.Department_or_branch_name
    
    objects = models.Manager()

Quiz/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import CustomizeQuiz, Tquestion, Myself, Slide
from django.contrib.auth.decorators import login_required
from cloudinary import CloudinaryImage
# Create your views here.
#Quiz
def Mquiz(request):
    quiz = CustomizeQuiz.objects.filter()
    arg = {
        'x': quiz[0]
    }
    return render(request, 'Quiz/quiz.html', arg)

@login_required(login_url="/account/login_view/")    
def question(request, that_quiz_id):
    that_quiz = CustomizeQuiz.objects.get(id=that_quiz_id)
    questions = Tquestion.objects.filter(that_Quiz=that_quiz)
    count = 0
    for x in questions:
        count += 1
    arg = {
        'that_quiz' : that_quiz,
        'questions': questions,
        'count' : count
    }
    return render(request, 'Quiz/questions.html', arg)

@login_required(login_url="/account/login_view/")
def Submission(request, that_quiz_id):
    if request.method == "POST":
        counter = questionCounter(that_quiz_id)

        Mystrlist = ""
        for x in range(1, counter + 1):
            Mystrlist += request.POST[str(x)]
        print(Mystrlist)

        answers = answerList(that_quiz_id)
        print(answers)
        
        analysisList = analysis(Mystrlist, answers, counter)

        correct = analysisList[0]
        wrong = analysisList[1]
        percentage = analysisList[2]

        print(correct,wrong,percentage)

        # quiz = CustomizeQuiz.objects.get(id=that_quiz_id)
        thatUser = request.user

        done = Myself(me=thatUser, answer=answers, correct=correct, wrong=wrong, percentage=percentage)
        done.save()
        # done = Notification(projectName=projectName, reqUser=reqUser, message=message,toAdmin=toAdmin)
        # done.save()
        # print(message,projectName,reqUser)
        verification = int(done.urlhash)
        print(done.urlhash)
        return redirect('Quiz:Score',verification=verification)

# # FUNCTIONS
def questionCounter(that_quiz_id):
    that_quiz = CustomizeQuiz.objects.get(id=that_quiz_id)
    all_question = Tquestion.objects.filter(that_Quiz=that_quiz)
    counter = 0
    for x in all_question:
        counter += 1
    return counter

def answerList(that_quiz_id):
    that_quiz = CustomizeQuiz.objects.get(id=that_quiz_id)
    all_question = Tquestion.objects.filter(that_Quiz=that_quiz)
    Anslist = ""
    for x in all_question:
        Anslist += x.answer[0]
    return Anslist

def analysis(Mystrlist, answers, counter):
    correct = 0
    wrong = 0
    for x in range(0, counter):
        if Mystrlist[x] == answers[x]:
            correct += 1
        else:
            wrong += 1
    percentage = int((correct*100)/counter)
    analysisList = [correct,wrong,percentage]
    return analysisList

# Slide
@login_required(login_url="/account/login_view/")
def slide(request, that_slide_no):
    that_quiz = CustomizeQuiz.objects.filter()
    that_quiz = that_quiz[0]
    that_slide = Slide.objects.filter(no=that_slide_no)
    #
    # img = cloudinary.CloudinaryImage(“sample”, format=“png”)
    #
    counter = SlideCounter()
    arg = {
        "slide": that_slide,
        "count": counter,
        "prev": that_slide_no - 1,
        "next": that_slide_no + 1,
        "that_quiz": that_quiz,
        # "that_slide_img" : that_slide_img
    }
    return render(request, 'Quiz/slide.html', arg)
    
def SlideCounter():
    counter = 0
    slides = Slide.objects.filter()
    for x in slides:
        counter += 1
    
    return counter

@login_required(login_url="/account/login_view/")
def certificate(request, verification):
    that_submit = Myself.objects.get(urlhash=verification)
    print(that_submit)
    return render(request, 'Quiz/Certificate.html', {
        'that_submit' : that_submit
    })

@login_required(login_url="/account/login_view/")
def Score(request, verification):
    that_submit = Myself.objects.get(urlhash=verification)
    print(that_submit)
    return render(request, 'Quiz/score.html', {
        'that_submit' : that_submit
    })

Quiz/templates/Quiz/Certificate.html
{% load static %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
<script src="https://superal.github.io/canvas2image/canvas2image.js"></script>
<link rel="stylesheet" href="{% static 'Quiz/Css/Certificate.css' %}">



<!-- <div class="Download" style="width: 1056px; height: 816px;" > -->
<div class="Download" style="width: 1056px; height:816px;">
		<div id="Certificate" >
			<img id="Red_Diploma_Certificate__3_" src="{% static 'Quiz/Images/Red_Diploma_Certificate__3_.png' %}">
			<div id="">
				<span></span>
			</div>
			<div id="Raihan_Chowdhury">
				<span>{{that_submit.me.full_name}}</span>
			</div>
			<div id="Raihan_Chowdhury_j">
				<span>Raihan Chowdhury</span>
			</div>
			<div id="Sadman_sakib_Jisan">
				<span>Sadman sakib Jisan</span>
			</div>
			<div id="Congratulation__You_have_obtai">
				<span>Congratulation, You have<br/>obtained {{that_submit.percentage}}% marks in this Quiz.</span><br>
			</div>
		</div>
</div>
<div class="cent">
	<button id="cBut" type="button" >
		<!-- <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13 8V2H7v6H2l8 8 8-8h-5zM0 18h20v2H0v-2z"/></svg> -->
		Download
	</button>
</div>

<script>
	document.getElementById('cBut').addEventListener('click', function() {
		html2canvas(document.querySelector('.Download'), {
			onrendered: function(canvas) {
				// document.body.appendChild(canvas);
			  return Canvas2Image.saveAsPNG(canvas);
			}
		});
		
	});
</script>
<style>
	.cent{
		display: flex;
		justify-content:center;
	}
	button {
		display: inline-block;
		font-size: 1.15em;
		position: relative;
		text-align: center;
		padding: 0.5em 1em;
		background: linear-gradient(45deg, #59adeb, #40c3af);
		color: #fff;
		box-shadow: 0 0.2em 0.2em rgba(0,0,0,0.25);
		border-radius: 0.2em;
		transition: box-shadow 0.2s ease-in-out;
		cursor: pointer;
	  }
	  button:hover {
		box-shadow: 0 0.1em 0.25em rgba(0,0,0,0.25);
	  }
</style>






<script src="{% static 'Quiz/js/Certificate.js' %}"></script>




	

Quiz/templates/Quiz/base.html
<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,500&display=swap" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=.7">

<style>
  .fire_font{
    font-family: 'Roboto', sans-serif;
  }

  nav{
    font-family: 'Roboto', sans-serif;
  }
  .dropdown:hover .dropdown-menu {
	display: block;
  }
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/material-icons.min.css" integrity="sha256-x8PYmLKD83R9T/sYmJn1j3is/chhJdySyhet/JuHnfY=" crossorigin="anonymous" />
<link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;700;900&display=swap" rel="stylesheet">
<style>
  html,
body {
  font-family: "Rubik", sans-serif;
}

/* navigation 
 - show navigation always on the large screen devices with (min-width:1024)
*/

@media (min-width: 1024px) {
  .top-navbar {
    display: inline-flex !important;
  }
}

</style>

<nav class="flex items-center bg-gray-800 p-3 flex-wrap">
      <a href="/" class="p-2 mr-4 inline-flex items-center">
        <svg
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
          class="fill-current text-white h-8 w-8 mr-2"
        >
          <path
            d="M12.001 4.8c-3.2 0-5.2 1.6-6 4.8 1.2-1.6 2.6-2.2 4.2-1.8.913.228 1.565.89 2.288 1.624C13.666 10.618 15.027 12 18.001 12c3.2 0 5.2-1.6 6-4.8-1.2 1.6-2.6 2.2-4.2 1.8-.913-.228-1.565-.89-2.288-1.624C16.337 6.182 14.976 4.8 12.001 4.8zm-6 7.2c-3.2 0-5.2 1.6-6 4.8 1.2-1.6 2.6-2.2 4.2-1.8.913.228 1.565.89 2.288 1.624 1.177 1.194 2.538 2.576 5.512 2.576 3.2 0 5.2-1.6 6-4.8-1.2 1.6-2.6 2.2-4.2 1.8-.913-.228-1.565-.89-2.288-1.624C10.337 13.382 8.976 12 6.001 12z"
          />
        </svg>
        <span class="text-md text-white font-bold uppercase tracking-wide"
          >Information Security Awareness</span
        >
      </a>
      <button
        class="text-white inline-flex p-3 hover:bg-gray-900 rounded lg:hidden ml-auto hover:text-white outline-none nav-toggler"
        data-target="#navigation"
      >
        <i class="material-icons">menu</i>
      </button>
      <div
        class="hidden top-navbar w-full lg:inline-flex lg:flex-grow lg:w-auto"
        id="navigation"
      >
        <div
          class="lg:inline-flex lg:flex-row lg:ml-auto lg:w-auto w-full lg:items-center items-start  flex flex-col lg:h-auto"
        >
          <a
            href="/"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span>Home</span>
          </a>

          {% if user.is_superuser %}  
          <a
            href="{% url 'account:analysis' %}"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span>Analytics dashboard</span>
          </a>
          {% endif %}

          {% if user.is_superuser %}  
          <a
            href="{% url 'account:adminPanel' %}"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span>Admin Panel</span>
          </a>
          {% endif %}

          {% if user.is_superuser %}  
          <a
            href="{% url 'account:adminDashboard' %}"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span>Dashboard</span>
          </a>
          {% endif %}

          {% if user.is_authenticated %}
          <a
            href="{% url 'account:mysubmissions' %}"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span>My Submissions</span>
          </a>
          {% endif %}
          {% if user.is_authenticated %}
          <a
          href="{% url 'account:change_password' %}"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span>Change Password</span>
          </a>
          {% endif %}
          {% if not user.is_authenticated %}
          <a
          href="{% url 'account:registration_view' %}"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span>Registration</span>
          </a>
          {% endif %}
          {% if not user.is_authenticated %}
          <a
            href="{% url 'account:login_view' %}"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span>Login</span>
          </a>
          {% endif %}
          {% if user.is_authenticated %}
          <a
            href="{% url 'account:logout_view' %}"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span>LogOut</span>
          </a>
          {% endif %}
        </div>
      </div>
    </nav>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
<script>
  $(document).ready(function() {
  $(".nav-toggler").each(function(_, navToggler) {
    var target = $(navToggler).data("target");
    $(navToggler).on("click", function() {
      $(target).animate({
        height: "toggle"
      });
    });
  });
});

</script>

{% block body %}
{% endblock %}

Quiz/templates/Quiz/questions.html
{% extends 'Quiz/base.html' %}
{% block body%}
{% load static %}
<style>

</style>
<div onclick="Startfunc()" id="start" class="flex justify-center">
    <button style="position:absolute; top:50vh" class="text-6xl bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded-lg">
      Start Now
    </button>
</div>
<form action="{% url 'Quiz:Submission' that_quiz_id=that_quiz.id %}" method="POST">
{% csrf_token %}
    {% for x in questions %}
<div id="Hid{{x.no}}" class="flex justify-center my-32 " style="display: none; ">
    <div class=" max-w-lg bg-white shadow-lg rounded-lg overflow-hidden my-10" style="min-width: 50vw;">
        <div class="px-4 py-8">
            <div class="flex justify-center">
                <h1 class="text-gray-400 font-bold text-3xl uppercase">{{x.no}}/{{count}}</h1>
            </div>
            <h1 class="text-gray-900 font-bold text-3xl uppercase">{{x.question}}</h1>
            <div class="flex items-center">
                <div class="mt-4">
                    <div class="mt-2">
                    <label class="ml-6">
                        <input type="radio" class="form-radio" name="{{x.no}}" value="A">
                        <span class="ml-2">{{x.A}}</span>
                    </label>
                    </div>
                    <div class="mt-2">
                        <label class="ml-6">
                            <input type="radio" class="form-radio" name="{{x.no}}" value="B">
                            <span class="ml-2">{{x.B}}</span>
                        </label>
                    </div>
                    <div class="mt-2">
                        <label class="ml-6">
                            <input type="radio" class="form-radio" name="{{x.no}}" value="C">
                            <span class="ml-2">{{x.C}}</span>
                        </label>
                    </div>
                    <div class="mt-2">
                        <label class="ml-6">
                            <input type="radio" class="form-radio" name="{{x.no}}" value="D">
                            <span class="ml-2">{{x.D}}</span>
                        </label>
                    </div>
                    <div class="mt-2">
                        <label class="ml-6">
                            <input type="radio" class="form-radio " name="{{x.no}}" value="E" checked>
                            <span class="ml-2 text-green-400 ">Pass</span>
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="flex justify-center py-8">
            <div id="back">
                <img onclick="changeBack()"  class="outline-none hover:opacity-75 m-8"  src="{% static 'Quiz/Images/b.png' %}">
            </div>
            {% if x.no != count %}
            <div id="next" >
                <img onclick="changeNext()"  class="outline-none hover:opacity-75 m-8" src="{% static 'Quiz/Images/f.png' %}">
            </div>
            {% endif %}

            {% if x.no == count %}
                <button class="my-4 bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold px-4 rounded-r">
                  Submit
                </button>
            {% endif %}
            
        </div>
    </div>
</div>
{% endfor %}
</form>

<script>
    var counter = 0;
    function Startfunc(){
        counter += 1;
        var x = document.getElementById("Hid1");
        x.style.display = "flex";
        var y = document.getElementById("start");
        y.style.display = "none";
        checkB(counter)
    }

    function changeNext(){
        old = counter
        oldDiv = "Hid" + old
        counter += 1;
        divId = "Hid" + String(counter)
        var x = document.getElementById(divId);
        var y = document.getElementById(oldDiv);
        if (x.style.display === "none") {
            x.style.display = "flex";
        } else {
            x.style.display = "none";
        }
        if (y.style.display === "none") {
        y.style.display = "flex";
        } else {
        y.style.display = "none";
        }
        console.log(old,counter,counter+1)
        checkB(counter)
        
    }
    function changeBack(){
        old = counter
        oldDiv = "Hid" + old
        counter -= 1;
        divId = "Hid" + String(counter)

        var x = document.getElementById(divId);
        var y = document.getElementById(oldDiv);
        if (x.style.display === "none") {
            x.style.display = "flex";
          } else {
            x.style.display = "none";
          }
        if (y.style.display === "none") {
        y.style.display = "flex";
        } else {
        y.style.display = "none";
        }
        checkB(counter)
    }



    function checkB(counter){
        if (counter == 1){
            var a = document.getElementById("back");
            a.style.display = "none"
        }
        else if (counter != 1){
            var a = document.getElementById("back");
            a.style.display = "flex";
        }
    }
</script>

{% endblock %}

/*
counter = 1;
    function Startfunc(){
        var x = document.getElementById("Hid1");
        if (x.style.display == "none") {
            x.style.display = "flex";
          } else {
            x.style.display = "none";
          }
        var y = document.getElementById("start");
        y.style.display = "none";
        check(counter)
        checkN(counter)
    }

    function changeNext(){
            old = counter
            oldDiv = "Hid" + old
            counter += 1;
            divId = "Hid" + String(counter)
            var x = document.getElementById(divId);
            var y = document.getElementById(oldDiv);
            if (x.style.display === "none") {
                x.style.display = "flex";
            } else {
                x.style.display = "none";
            }
            if (y.style.display === "none") {
            y.style.display = "flex";
            } else {
            y.style.display = "none";
            }
            console.log(old,counter,counter+1)

            check(counter)
            checkN(counter)
    }

    function changeBack(){
        old = counter
        oldDiv = "Hid" + old
        counter -= 1;
        divId = "Hid" + String(counter)

        var x = document.getElementById(divId);
        var y = document.getElementById(oldDiv);
        if (x.style.display === "none") {
            x.style.display = "flex";
          } else {
            x.style.display = "none";
          }
        if (y.style.display === "none") {
        y.style.display = "flex";
        } else {
        y.style.display = "none";
        }
        check(counter)
        checkN(counter)
    }

    function checkB(counter){
        if (counter == 1){
            let back = document.getElementById("back");
            back.style.display = "none";
        }
    }
    function checkN(counter){
        if (counter != 4){
            let nextQ = document.getElementById("nextQ");
            nextQ.style.display = "flex";
        }
    }
        
*/

Quiz/templates/Quiz/quiz.html
{% extends 'Quiz/base.html' %}
{% block body%}
<div class="flex justify-center">
    <div class="p-12 max-w-full bg-white shadow-lg rounded-lg overflow-hidden my-10">
        <div class="px-4 py-2 ">
            <h1 class="text-gray-900 font-bold text-3xl uppercase">{{x.title}}</h1>
            <div class="flex items-center">
                <p class=" text-gray-600 text-xl mt-1">{{x.description}}</p>
            </div>
        </div>
        <!-- <img class="h-56 w-full object-cover mt-2" src="https://images.unsplash.com/photo-1526379095098-d400fd0bf935?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="NIKE AIR"> -->
        <div class="flex items-center justify-between px-4 py-2 bg-gray-900">
            <h1 class="text-gray-200 font-bold text-xl"></h1>
            <a href="{% url 'Quiz:slide' that_slide_no=1 %}">
                <button class="px-6 py-2 bg-gray-200 text-xl text-gray-900 font-semibold rounded">Start Quiz</button>
            </a>
        </div>
    </div>
</div>

{% endblock %}

Quiz/templates/Quiz/slide.html
{% extends 'Quiz/base.html' %}
{% block body%}
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=.5">



{% for x in slide %}
<div class="flex justify-center my-32 ">
    <div class="w-11/12 max-w-6xl bg-white shadow-2xl rounded-lg overflow-hidden my-10 py-4 px-8" style="min-width: 50vw;">
        <div class="px-4 py-8">
            <div class="flex justify-center">
                <h1 class="text-gray-900 font-bold text-3xl uppercase">{{x.title}}</h1>
            </div>   
        </div>
        {% if x.image %}
            <div class="flex justify-center">
                
                <img src="{{x.image.url}}" alt="" style="width: 100% !important; height:auto !important;">
            </div>
        {% endif %}
            <div class="my-12">
                <p class=" text-gray-600 text-xl mt-1 ">{{x.description}}</p>
            </div>
        <div class="flex justify-center py-8">  
            {% if x.no != 1 %}
                <div id="back">
                    <a href="{% url 'Quiz:slide' that_slide_no=prev %}">
                        <img  class="outline-none hover:opacity-75 m-8"  src="{% static 'Quiz/Images/b.png' %}">
                    </a>
                </div>
            {% endif %}
            {% if x.no != count %}
                <div id="next" >
                    <a href="{% url 'Quiz:slide' that_slide_no=next %}">
                        <img  class="outline-none hover:opacity-75 m-8" src="{% static 'Quiz/Images/f.png' %}">
                    </a>
                </div>
            {% endif %}
    
            {% if x.no == count %}
            <a href="{% url 'Quiz:question' that_quiz_id=that_quiz.id %}">
                <button  class="my-4 py-4 bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold px-4 rounded-r">
                    Start Quiz
                </button>
            </a>
            {% endif %}
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}